//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsAVD
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsAVD.utilityFERCSoap")]
    public interface utilityFERCSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getComprobantes", ReplyAction="*")]
        System.Threading.Tasks.Task<wsAVD.getComprobantesResponse> getComprobantesAsync(wsAVD.getComprobantesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAcuses", ReplyAction="*")]
        System.Threading.Tasks.Task<wsAVD.getAcusesResponse> getAcusesAsync(wsAVD.getAcusesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getComprobantesRE", ReplyAction="*")]
        System.Threading.Tasks.Task<wsAVD.getComprobantesREResponse> getComprobantesREAsync(wsAVD.getComprobantesRERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/postGenerarEstadoComercial", ReplyAction="*")]
        System.Threading.Tasks.Task<wsAVD.postGenerarEstadoComercialResponse> postGenerarEstadoComercialAsync(wsAVD.postGenerarEstadoComercialRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getComprobantesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getComprobantes", Namespace="http://tempuri.org/", Order=0)]
        public wsAVD.getComprobantesRequestBody Body;
        
        public getComprobantesRequest()
        {
        }
        
        public getComprobantesRequest(wsAVD.getComprobantesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getComprobantesRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FechaInicial;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FechaFinal;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string IdEmisor;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Consecutivo;
        
        public getComprobantesRequestBody()
        {
        }
        
        public getComprobantesRequestBody(string usuario, string password, string FechaInicial, string FechaFinal, string Consecutivo,string IdEmisor )
        {
            this.usuario = usuario;
            this.password = password;
            this.FechaInicial = FechaInicial;
            this.FechaFinal = FechaFinal;
            this.IdEmisor = IdEmisor;
            this.Consecutivo = Consecutivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getComprobantesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getComprobantesResponse", Namespace="http://tempuri.org/", Order=0)]
        public wsAVD.getComprobantesResponseBody Body;
        
        public getComprobantesResponse()
        {
        }
        
        public getComprobantesResponse(wsAVD.getComprobantesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getComprobantesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getComprobantesResult;
        
        public getComprobantesResponseBody()
        {
        }
        
        public getComprobantesResponseBody(string getComprobantesResult)
        {
            this.getComprobantesResult = getComprobantesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAcusesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAcuses", Namespace="http://tempuri.org/", Order=0)]
        public wsAVD.getAcusesRequestBody Body;
        
        public getAcusesRequest()
        {
        }
        
        public getAcusesRequest(wsAVD.getAcusesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAcusesRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FechaInicial;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FechaFinal;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order=4)]
        public string IdEmisor;

        public getAcusesRequestBody()
        {
        }
        
        public getAcusesRequestBody(string usuario, string password, string FechaInicial, string FechaFinal, string IdEmisor)
        {
            this.usuario = usuario;
            this.password = password;
            this.FechaInicial = FechaInicial;
            this.FechaFinal = FechaFinal;
            this.IdEmisor = IdEmisor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAcusesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAcusesResponse", Namespace="http://tempuri.org/", Order=0)]
        public wsAVD.getAcusesResponseBody Body;
        
        public getAcusesResponse()
        {
        }
        
        public getAcusesResponse(wsAVD.getAcusesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAcusesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getAcusesResult;
        
        public getAcusesResponseBody()
        {
        }
        
        public getAcusesResponseBody(string getAcusesResult)
        {
            this.getAcusesResult = getAcusesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getComprobantesRERequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getComprobantesRE", Namespace="http://tempuri.org/", Order=0)]
        public wsAVD.getComprobantesRERequestBody Body;
        
        public getComprobantesRERequest()
        {
        }
        
        public getComprobantesRERequest(wsAVD.getComprobantesRERequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getComprobantesRERequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cContrasena;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cFechaInicio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cFechaFinal;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string cIdReceptor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string cIdEmisor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string cClave;
        
        public getComprobantesRERequestBody()
        {
        }
        
        public getComprobantesRERequestBody(string cUsuario, string cContrasena, string cFechaInicio, string cFechaFinal, string cIdReceptor, string cIdEmisor, string cClave)
        {
            this.cUsuario = cUsuario;
            this.cContrasena = cContrasena;
            this.cFechaInicio = cFechaInicio;
            this.cFechaFinal = cFechaFinal;
            this.cIdReceptor = cIdReceptor;
            this.cIdEmisor = cIdEmisor;
            this.cClave = cClave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getComprobantesREResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getComprobantesREResponse", Namespace="http://tempuri.org/", Order=0)]
        public wsAVD.getComprobantesREResponseBody Body;
        
        public getComprobantesREResponse()
        {
        }
        
        public getComprobantesREResponse(wsAVD.getComprobantesREResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getComprobantesREResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getComprobantesREResult;
        
        public getComprobantesREResponseBody()
        {
        }
        
        public getComprobantesREResponseBody(string getComprobantesREResult)
        {
            this.getComprobantesREResult = getComprobantesREResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class postGenerarEstadoComercialRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="postGenerarEstadoComercial", Namespace="http://tempuri.org/", Order=0)]
        public wsAVD.postGenerarEstadoComercialRequestBody Body;
        
        public postGenerarEstadoComercialRequest()
        {
        }
        
        public postGenerarEstadoComercialRequest(wsAVD.postGenerarEstadoComercialRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class postGenerarEstadoComercialRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cContrasena;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cClave;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cEstado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string cMotivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string cCorreoNotificar;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string cTipoIdReceptor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string cIdReceptor;
        
        public postGenerarEstadoComercialRequestBody()
        {
        }
        
        public postGenerarEstadoComercialRequestBody(string cUsuario, string cContrasena, string cClave, string cEstado, string cMotivo, string cCorreoNotificar, string cTipoIdReceptor, string cIdReceptor)
        {
            this.cUsuario = cUsuario;
            this.cContrasena = cContrasena;
            this.cClave = cClave;
            this.cEstado = cEstado;
            this.cMotivo = cMotivo;
            this.cCorreoNotificar = cCorreoNotificar;
            this.cTipoIdReceptor = cTipoIdReceptor;
            this.cIdReceptor = cIdReceptor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class postGenerarEstadoComercialResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="postGenerarEstadoComercialResponse", Namespace="http://tempuri.org/", Order=0)]
        public wsAVD.postGenerarEstadoComercialResponseBody Body;
        
        public postGenerarEstadoComercialResponse()
        {
        }
        
        public postGenerarEstadoComercialResponse(wsAVD.postGenerarEstadoComercialResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class postGenerarEstadoComercialResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string postGenerarEstadoComercialResult;
        
        public postGenerarEstadoComercialResponseBody()
        {
        }
        
        public postGenerarEstadoComercialResponseBody(string postGenerarEstadoComercialResult)
        {
            this.postGenerarEstadoComercialResult = postGenerarEstadoComercialResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface utilityFERCSoapChannel : wsAVD.utilityFERCSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class utilityFERCSoapClient : System.ServiceModel.ClientBase<wsAVD.utilityFERCSoap>, wsAVD.utilityFERCSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public utilityFERCSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(utilityFERCSoapClient.GetBindingForEndpoint(endpointConfiguration), utilityFERCSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public utilityFERCSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(utilityFERCSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public utilityFERCSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(utilityFERCSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public utilityFERCSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsAVD.getComprobantesResponse> wsAVD.utilityFERCSoap.getComprobantesAsync(wsAVD.getComprobantesRequest request)
        {
            return base.Channel.getComprobantesAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsAVD.getComprobantesResponse> getComprobantesAsync(string usuario, string password, string FechaInicial, string FechaFinal, string IdEmisor, string Consecutivo)
        {
            wsAVD.getComprobantesRequest inValue = new wsAVD.getComprobantesRequest();
            inValue.Body = new wsAVD.getComprobantesRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            inValue.Body.FechaInicial = FechaInicial;
            inValue.Body.FechaFinal = FechaFinal;
            inValue.Body.IdEmisor = IdEmisor;
            inValue.Body.Consecutivo = Consecutivo;
            return ((wsAVD.utilityFERCSoap)(this)).getComprobantesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsAVD.getAcusesResponse> wsAVD.utilityFERCSoap.getAcusesAsync(wsAVD.getAcusesRequest request)
        {
            return base.Channel.getAcusesAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsAVD.getAcusesResponse> getAcusesAsync(string usuario, string password, string FechaInicial, string FechaFinal, string IdEmisor)
        {
            wsAVD.getAcusesRequest inValue = new wsAVD.getAcusesRequest();
            inValue.Body = new wsAVD.getAcusesRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            inValue.Body.FechaInicial = FechaInicial;
            inValue.Body.FechaFinal = FechaFinal;
            inValue.Body.IdEmisor = IdEmisor;
            return ((wsAVD.utilityFERCSoap)(this)).getAcusesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsAVD.getComprobantesREResponse> wsAVD.utilityFERCSoap.getComprobantesREAsync(wsAVD.getComprobantesRERequest request)
        {
            return base.Channel.getComprobantesREAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsAVD.getComprobantesREResponse> getComprobantesREAsync(string cUsuario, string cContrasena, string cFechaInicio, string cFechaFinal, string cIdReceptor, string cIdEmisor, string cClave)
        {
            wsAVD.getComprobantesRERequest inValue = new wsAVD.getComprobantesRERequest();
            inValue.Body = new wsAVD.getComprobantesRERequestBody();
            inValue.Body.cUsuario = cUsuario;
            inValue.Body.cContrasena = cContrasena;
            inValue.Body.cFechaInicio = cFechaInicio;
            inValue.Body.cFechaFinal = cFechaFinal;
            inValue.Body.cIdReceptor = cIdReceptor;
            inValue.Body.cIdEmisor = cIdEmisor;
            inValue.Body.cClave = cClave;
            return ((wsAVD.utilityFERCSoap)(this)).getComprobantesREAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsAVD.postGenerarEstadoComercialResponse> wsAVD.utilityFERCSoap.postGenerarEstadoComercialAsync(wsAVD.postGenerarEstadoComercialRequest request)
        {
            return base.Channel.postGenerarEstadoComercialAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsAVD.postGenerarEstadoComercialResponse> postGenerarEstadoComercialAsync(string cUsuario, string cContrasena, string cClave, string cEstado, string cMotivo, string cCorreoNotificar, string cTipoIdReceptor, string cIdReceptor)
        {
            wsAVD.postGenerarEstadoComercialRequest inValue = new wsAVD.postGenerarEstadoComercialRequest();
            inValue.Body = new wsAVD.postGenerarEstadoComercialRequestBody();
            inValue.Body.cUsuario = cUsuario;
            inValue.Body.cContrasena = cContrasena;
            inValue.Body.cClave = cClave;
            inValue.Body.cEstado = cEstado;
            inValue.Body.cMotivo = cMotivo;
            inValue.Body.cCorreoNotificar = cCorreoNotificar;
            inValue.Body.cTipoIdReceptor = cTipoIdReceptor;
            inValue.Body.cIdReceptor = cIdReceptor;
            return ((wsAVD.utilityFERCSoap)(this)).postGenerarEstadoComercialAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.utilityFERCSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.utilityFERCSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.utilityFERCSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://cabecar.avdcloud.com/WS_GESSA_CR/utilityFERC.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.utilityFERCSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://cabecar.avdcloud.com/WS_GESSA_CR/utilityFERC.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            utilityFERCSoap,
            
            utilityFERCSoap12,
        }
    }
}
